spring.application.name=postsService

server.port=9021
server.servlet.context-path=/posts

#spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
#spring.datasource.username=postgres
#spring.datasource.password=surajnarale


spring.datasource.url=${POSTS_SERVICE_DB_URL}
spring.datasource.username:${POSTS_DB_USERNAME}
spring.datasource.password:${POSTS_DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9024/eureka/}
