spring.application.name=postsService

server.port=9021
server.servlet.context-path=/api/v1/posts

spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.datasource.username=postgres
spring.datasource.password=surajnarale


spring.jpa.hibernate.ddl-auto=update