spring.application.name=notification-service


server.port=9040
server.servlet.context-path=/notifications

#spring.datasource.url=jdbc:postgresql://localhost:5432/notificationDB
#spring.datasource.username=postgres
#spring.datasource.password=surajnarale

spring.datasource.url=${NOTI_SERVICE_DB_URL}
spring.datasource.username:${NOTI_DB_USERNAME:postgres}
spring.datasource.password:${NOTI_DB_PASSWORD:surajnarale}

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9024/eureka/}
