spring.application.name=userService

server.port=9022

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=surajnarale


spring.jpa.hibernate.ddl-auto=update
