spring.application.name=userService

server.port=9022

#spring.datasource.url=jdbc:postgresql://user_db:5432/userDB
#spring.datasource.username=postgres
#spring.datasource.password=surajnarale

spring.datasource.url=${USER_SERVICE_DB_URL}
spring.datasource.username:${USER_DB_USERNAME}
spring.datasource.password:${USER_DB_PASSWORD}


server.servlet.context-path=/user

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=jnewjknjdnejknk3nfn34rui43riuh34r34yry43r34hfhiuehfu4j438rm3h4rsh34hi5uh92t3298rod22b1a1a3ur8x124orij

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9024/eureka/}
